name: Deploy Worker
on:
  repository_dispatch:
  push:
    branches: ["main"]
  release:
    types: ["published"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - run: sed -i "s/KV_NAME/${{ secrets.KV_NAME }}/g" wrangler.toml
      - run: cat wrangler.toml
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
